### ISSUE TITLE
package does not exist: gradle

### ISSUE THREAD

**Issue by athaun** [crykn/kryonet#10]
I am trying to migrate from the main repository to here in my project.
I have changed my build.gradle to the following and already had jitpack/maven in my repos:
```
dependencies {
...
    implementation 'com.github.crykn:kryonet:2.22.8'
}
```
This is the error I get when trying to run:
```
/Users/asher/code/computer_science/2023/chess/src/main/java/network/KryoRegister.java:5: error: package com.esotericsoftware.kryo does not exist
import com.esotericsoftware.kryo.Kryo;
                                ^
/Users/asher/code/computer_science/2023/chess/src/main/java/network/KryoRegister.java:23: error: cannot find symbol
    private static void registerWithKryo (Kryo kryo) {
                                          ^
  symbol:   class Kryo
  location: class KryoRegister
/Users/asher/code/computer_science/2023/chess/src/main/java/network/KryoRegister.java:49: error: cannot find symbol
        Kryo kryo = client.getKryo();
        ^
  symbol:   class Kryo
  location: class KryoRegister
/Users/asher/code/computer_science/2023/chess/src/main/java/network/KryoRegister.java:54: error: cannot find symbol
        Kryo kryo = server.getKryo();
        ^
  symbol:   class Kryo
  location: class KryoRegister
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
4 errors
```

My imports in the class KryoRegister look like so:
```
import com.esotericsoftware.kryo.Kryo;
import com.esotericsoftware.kryonet.Client;
import com.esotericsoftware.kryonet.Server;
```
Should my imports look different?
Thanks.

**Comment by crykn** [comment]
According to your error messages the only classes it can't find are the ones of Kryo itself and not the ones of KryoNet, which is odd. Even though the fork depends on a newer version of Kryo, that shouldn't change any of the package names. 

You could try using the Gradle dependencies task (`./gradlew depedencies`, IIRC) to make sure that Kryo is pulled in as a transitive dependency.

**Comment by athaun** [comment]
Although kryo was listed in the dependencies command, it still wouldn't run.
Adding an implementation for kryo seems to resolve the problem.
Thanks! 
```
implementation 'com.github.crykn:kryonet:2.22.8'
implementation 'com.esotericsoftware:kryo:5.5.0'
```
