### ISSUE TITLE
Is there an easy way to do P2P with this ?

### ISSUE THREAD

**Issue by tbvns** [crykn/kryonet#12]
I really need to do hole punching, but I have no idea how I am supposed to do that with KryoNet and the documentation doesn't mention anything about it either. I already understand the idea behind hole punching, but to make it work, a kryo client should be able to connect to another kryo client and all that kind of complicated stuff. Can a kryo client connect to another kryo client ? If not, will P2P ever be added to this project ?

**Comment by tbvns** [comment]
I'm going to take a look at this thing called UPnP, this look pretty useful. I'll close this issue if it resolves my needs.

**Comment by crykn** [comment]
> ...but to make it work, a kryo client should be able to connect to another kryo client and all that kind of complicated stuff. Can a kryo client connect to another kryo client ?

Two clients obviously can't connect to each other. But you can just create a server on the client side as well and use that. If you're just doing this for hole punching, you might not even need a local server and just sending the message to the client (without handling it there) suffices.

**Comment by tbvns** [comment]
I opted for upnp, I know it has some bad sides but it makes things so much easier. Thanks anyway!
