### ISSUE TITLE
Unable to build project

### ISSUE THREAD

**Issue by Betalord** [crykn/kryonet#9]
I'm trying to build the latest release KryoNet 2.22.7 to give this project a try, however I can't get it to build. I am trying to create a jar file to include with my project. This is the output the gradlew.bat gives me when issuing "gradlew build":

> E:\Eclipse\workspace\Supergalactix\Supergalactix-core\jars\kryonet-2.22.7>gradlew build
> Configuration on demand is an incubating feature.
> Download https://repo.maven.apache.org/maven2/com/esotericsoftware/kryo/5.0.0/kryo-5.0.0.pom
> Download https://repo.maven.apache.org/maven2/com/esotericsoftware/reflectasm/1.11.9/reflectasm-1.11.9.pom
> Download https://repo.maven.apache.org/maven2/org/sonatype/oss/oss-parent/7/oss-parent-7.pom
> Download https://repo.maven.apache.org/maven2/com/esotericsoftware/kryo-parent/5.0.0/kryo-parent-5.0.0.pom
> Download https://jitpack.io/com/github/esotericsoftware/jsonbeans/0.9/jsonbeans-0.9.pom
> Download https://repo.maven.apache.org/maven2/org/objenesis/objenesis/3.0.1/objenesis-3.0.1.pom
> Download https://repo.maven.apache.org/maven2/com/esotericsoftware/minlog/1.3.1/minlog-1.3.1.pom
> Download https://repo.maven.apache.org/maven2/org/objenesis/objenesis-parent/3.0.1/objenesis-parent-3.0.1.pom
> Download https://repo.maven.apache.org/maven2/org/objenesis/objenesis/3.0.1/objenesis-3.0.1.jar
> Download https://repo.maven.apache.org/maven2/com/esotericsoftware/minlog/1.3.1/minlog-1.3.1.jar
> Download https://repo.maven.apache.org/maven2/com/esotericsoftware/reflectasm/1.11.9/reflectasm-1.11.9.jar
> Download https://repo.maven.apache.org/maven2/com/esotericsoftware/kryo/5.0.0/kryo-5.0.0.jar
> Download https://jitpack.io/com/github/esotericsoftware/jsonbeans/0.9/jsonbeans-0.9.jar
> 
> > Task :compileJava
> Note: Some input files use unchecked or unsafe operations.
> Note: Recompile with -Xlint:unchecked for details.
> Download https://repo.maven.apache.org/maven2/junit/junit/4.12/junit-4.12.pom
> Download https://repo.maven.apache.org/maven2/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.pom
> Download https://repo.maven.apache.org/maven2/org/hamcrest/hamcrest-parent/1.3/hamcrest-parent-1.3.pom
> Download https://repo.maven.apache.org/maven2/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar
> Download https://repo.maven.apache.org/maven2/junit/junit/4.12/junit-4.12.jar
> 
> > Task :compileTestJava
> Note: Some input files use unchecked or unsafe operations.
> Note: Recompile with -Xlint:unchecked for details.
> 
> > Task :test
> 
> com.esotericsoftware.kryonet.JsonTest > testJson FAILED
>     junit.framework.AssertionFailedError: TCP data is not equal on client. (expected: Data, actual: Data)
>         at junit.framework.Assert.fail(Assert.java:57)
>         at junit.framework.TestCase.fail(TestCase.java:227)
>         at com.esotericsoftware.kryonet.JsonTest.testJson(JsonTest.java:115)
> 
> 23 tests completed, 1 failed
> 
> > Task :test FAILED
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':test'.
> > There were failing tests. See the report at: file:///E:/Eclipse/workspace/Supergalactix/Supergalactix-core/jars/kryonet-2.22.7/build/reports/tests/test/index.html
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
> Use '--warning-mode all' to show the individual deprecation warnings.
> See https://docs.gradle.org/4.9/userguide/command_line_interface.html#sec:command_line_warnings
> 
> BUILD FAILED in 2m 9s
> 4 actionable tasks: 4 executed

**Comment by crykn** [comment]
Hey @Betalord,

I just had a look at it and apparently running the tests via `gradle test` had some issues with the encoding. That only seems to happen locally (because the CI still builds without issues) and running the tests directly via Eclipse also works flawlessly, which is why I never noticed this before. Regardless – in general, I'd advise against running the tests before every build, because some of the tests take quite a long time to complete.

**Comment by Betalord** [comment]
OK, since I'm new to Gradle and kryonet (well, your fork of it), I'd just like to build my jar that includes all the libraries needed etc. so that I can use it with my project. What must I do?
Or better, can I download the jar from somewhere or can you provide one?

**Comment by crykn** [comment]
If you are using one of the common dependency management/build tools (like Maven or Gradle) for your project, you can import the fork pretty easily. Just check out the instructions [here](https://jitpack.io/#crykn/kryonet/2.22.8).

If you don't (which I wouldn't really recommend, but whatever), you can download a jar for version 2.22.8 [here](https://jitpack.io/com/github/crykn/kryonet/2.22.8/kryonet-2.22.8.jar). Then you'd also need the jars for [Kryo](https://github.com/EsotericSoftware/kryo) and [jsonbeans](https://jitpack.io/com/github/EsotericSoftware/jsonbeans/c3520fcc51/jsonbeans-c3520fcc51.jar) as well as for Kryo's dependencies.

**Comment by Betalord** [comment]
I did that and it works. Another question: what is the minimum JDK needed to use this kyronet fork? I see that kryo 5.0.0 requires JDK 11 to build, so I assume same for kryonet?

**Comment by crykn** [comment]
JRE 8 is the minimum version supported by both projects.
